In [4]:
import numpy as np 

X = np.random.randn(20,1)
X.shape

(20, 1)

In [11]:
X[...,0].shape

(20,)

In [21]:
X = np.random.randn(20,3)
X[:,1:].shape

(20, 2)

In [31]:
test = np.random.randint(1,6,10 )
test

array([2, 1, 5, 2, 3, 1, 5, 2, 1, 3])

In [33]:
test2 = np.random.randint(1,6,10)
test2

array([2, 2, 3, 1, 2, 2, 1, 3, 4, 1])

In [34]:
np.where(test < 5)[0]

array([0, 1, 3, 4, 5, 7, 8, 9], dtype=int64)

In [35]:
test2[np.where(test < 5)[0]]


array([2, 2, 1, 2, 2, 3, 4, 1])

In [36]:
test2

array([2, 2, 3, 1, 2, 2, 1, 3, 4, 1])

In [37]:
np.where(test < 5)

(array([0, 1, 3, 4, 5, 7, 8, 9], dtype=int64),)