In [4]:
import numpy as np 

X = np.random.randn(20,1)
X.shape

(20, 1)

In [11]:
X[...,0].shape

(20,)

In [21]:
X = np.random.randn(20,3)
X[:,1:].shape

(20, 2)

In [31]:
test = np.random.randint(1,6,10 )
test

array([2, 1, 5, 2, 3, 1, 5, 2, 1, 3])

In [33]:
test2 = np.random.randint(1,6,10)
test2

array([2, 2, 3, 1, 2, 2, 1, 3, 4, 1])

In [34]:
np.where(test < 5)[0]

array([0, 1, 3, 4, 5, 7, 8, 9], dtype=int64)

In [35]:
test2[np.where(test < 5)[0]]


array([2, 2, 1, 2, 2, 3, 4, 1])

In [36]:
test2

array([2, 2, 3, 1, 2, 2, 1, 3, 4, 1])

In [37]:
np.where(test < 5)

(array([0, 1, 3, 4, 5, 7, 8, 9], dtype=int64),)

In [13]:
import numpy as np 

x = np.ones(1)
my_list = []
for i in range(5):
    x*=2
    print(hex(id(x)))
    my_list.append(x)
    print(my_list)

0x10e00a610
[array([2.])]
0x10e00a610
[array([4.]), array([4.])]
0x10e00a610
[array([8.]), array([8.]), array([8.])]
0x10e00a610
[array([16.]), array([16.]), array([16.]), array([16.])]
0x10e00a610
[array([32.]), array([32.]), array([32.]), array([32.]), array([32.])]


In [12]:

x = 1
my_list = []
for i in range(5):
    x*=2
    print(hex(id(x)))
    my_list.append(x)
    print(my_list)

0x10abf4110
[2]
0x10abf4150
[2, 4]
0x10abf41d0
[2, 4, 8]
0x10abf42d0
[2, 4, 8, 16]
0x10abf44d0
[2, 4, 8, 16, 32]


In [5]:
x

array([32.])

In [2]:
x

array([2.])